version: '3.6'
services:
  db:
    build: db-server/ #使用此目錄內 dockerfile 建構的image 建構服務
    restart: always
    # ports:
      # - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin
    restart: always
    # ports:
      # - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=http://localhost/projectb-phpmyadmin/
    depends_on:
      - db

  backend:
    build: express-api/
    restart: always
    # ports:
      # - 3000:3000
    depends_on:
      - db

#vue部分若有更動內容要執行需要手動進行build 產生dist
#進入vue-main 執行 npm run build
  vue-main:
    build: vue-main/
    restart: always
    # ports:
      # - 3006:80
    depends_on:
      - db
      - backend

  nginx:
    build: nginx/
    restart: always
    ports:
      - 80:80